[project]
name = "asyncgui-ext-queue"
version = "0.3.1"
description = "An asyncio.Queue equivalent for asyncgui"
authors = [{ name = "Nattōsai Mitō", email = "flow4re2c@gmail.com" }]
requires-python = ">=3.10,<4"
readme = "README.md"
license = "MIT"
keywords = ["async"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "License :: OSI Approved :: MIT License",
    "Intended Audience :: Developers",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Software Development :: Libraries",
    "Operating System :: OS Independent",
]
dependencies = ["asyncgui>=0.9.3,<1.0.0"]

[project.urls]
Documentation = "https://asyncgui.github.io/asyncgui-ext-queue"
Repository = "https://github.com/asyncgui/asyncgui-ext-queue"

[dependency-groups]
dev = ["pytest>=8.0,<9"]
doc = [
    "sphinx>=7.2.6,<8",
    "furo>=2023.9.10,<2024",
]

[tool.uv]
default-groups = ["dev", ]

[tool.uv.build-backend]
module-name = "asyncgui_ext"
namespace = true

[build-system]
requires = ["uv_build>=0.9.2,<0.10.0"]
build-backend = "uv_build"

[tool.pytest.ini_options]
xfail_strict = true
addopts = "--maxfail=4 --strict-markers"
